name: docker-build

on:
  push:
  pull_request:

jobs:
  multi-arch-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # pin @ v6.0.1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # pin @ v3.12.0
      - 
        name: Login to GitHub Registry
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # pin @ v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Bake image
        uses: docker/bake-action@5be5f02ff8819ecd3092ea6b2e6261c31774f2b4 # pin @ v6.10.0
        env:
          MULTI_PLATFORM: true
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
